/* tslint:disable */
/* eslint-disable */
/**
 * BizimRehber API
 * The BizimRehber API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export * from './api/app-api';

