/* tslint:disable */
/* eslint-disable */
/**
 * Supply Chain - Logistics API
 * The Supply Chain - Logistics API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AllPickUpPointResponseDto
 */
export interface AllPickUpPointResponseDto {
    /**
     * 
     * @type {string}
     * @memberof AllPickUpPointResponseDto
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof AllPickUpPointResponseDto
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof AllPickUpPointResponseDto
     */
    'address': string;
    /**
     * 
     * @type {string}
     * @memberof AllPickUpPointResponseDto
     */
    'city': string;
    /**
     * 
     * @type {string}
     * @memberof AllPickUpPointResponseDto
     */
    'zipCode': string;
    /**
     * 
     * @type {string}
     * @memberof AllPickUpPointResponseDto
     */
    'country': string;
    /**
     * 
     * @type {number}
     * @memberof AllPickUpPointResponseDto
     */
    'latitude': number;
    /**
     * 
     * @type {number}
     * @memberof AllPickUpPointResponseDto
     */
    'longitude': number;
    /**
     * 
     * @type {string}
     * @memberof AllPickUpPointResponseDto
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof AllPickUpPointResponseDto
     */
    'updatedAt': string;
}

