/* tslint:disable */
/* eslint-disable */
/**
 * Supply Chain - Logistics API
 * The Supply Chain - Logistics API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AllVehiclesResponseDto
 */
export interface AllVehiclesResponseDto {
    /**
     * 
     * @type {string}
     * @memberof AllVehiclesResponseDto
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof AllVehiclesResponseDto
     */
    'name': string;
    /**
     * 
     * @type {object}
     * @memberof AllVehiclesResponseDto
     */
    'type': object;
    /**
     * 
     * @type {number}
     * @memberof AllVehiclesResponseDto
     */
    'pricePerKm': number;
    /**
     * 
     * @type {number}
     * @memberof AllVehiclesResponseDto
     */
    'pricePerHour': number;
    /**
     * 
     * @type {number}
     * @memberof AllVehiclesResponseDto
     */
    'capacityInKg': number;
    /**
     * 
     * @type {number}
     * @memberof AllVehiclesResponseDto
     */
    'capacityInM3': number;
    /**
     * 
     * @type {boolean}
     * @memberof AllVehiclesResponseDto
     */
    'available': boolean;
}

