/* tslint:disable */
/* eslint-disable */
/**
 * Supply Chain - Logistics API
 * The Supply Chain - Logistics API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateVehicleRequestDto
 */
export interface CreateVehicleRequestDto {
    /**
     * 
     * @type {string}
     * @memberof CreateVehicleRequestDto
     */
    'type': CreateVehicleRequestDtoTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateVehicleRequestDto
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof CreateVehicleRequestDto
     */
    'pricePerKm': number;
    /**
     * 
     * @type {number}
     * @memberof CreateVehicleRequestDto
     */
    'pricePerHour': number;
    /**
     * 
     * @type {number}
     * @memberof CreateVehicleRequestDto
     */
    'capacityInKg': number;
    /**
     * 
     * @type {number}
     * @memberof CreateVehicleRequestDto
     */
    'capacityInM3': number;
    /**
     * 
     * @type {boolean}
     * @memberof CreateVehicleRequestDto
     */
    'available': boolean;
}

/**
    * @export
    * @enum {string}
    */
export enum CreateVehicleRequestDtoTypeEnum {
    CAR = 'CAR',
    TRUCK = 'TRUCK'
}


